version: '3.8'

services:
  db:
    image: postgres:14
    container_name: libr_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: libr
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: libr_api
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - connection_string=postgres://postgres:abcd@db:5432/libr?sslmode=disable
